spring:
  application:
    name: zuul
server:
  port: 9999

# with zuul routes we can confgigure routes to use instead of defaults  
zuul:
  routes:
    # logical name for a service
    movies: 
      path: /movies
    # if no discovert, we have known where aps is running
    # url: http://localhost:8080\
    
    # if you have discovery, Zuul asks Eureka for the URL
      service-id: movies #lines up with spring.application.name
    
    # remove whatever zuul.rutes.movies.path says from url
    # /movies/api/v1.0 translated iinto /api/v1.0
      strip-prefix: true #true is default
  
      
